### ISSUE TITLE
Initialization

### ISSUE THREAD

**Issue by vekseel** [daochild/tronweb-typescript#3]
Hello! How to properly create a TronWeb instance? I get an error

![image](https://github.com/daochild/tronweb-typescript/assets/48432436/1582e255-d9b3-486c-a5fa-61f70451f871)

![image](https://github.com/daochild/tronweb-typescript/assets/48432436/1ae76ed3-6362-4e16-ae01-8437082e7cff)

**Comment by daochild** [comment]
try add type directly like in example
`///<reference path="node_modules/@daochild/tronweb-typescript/dist/index.d.ts"/>`

Files in test project

```json
{
  "name": "test-npm",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "build": "npm run build-ts",
    "test": "jest --coverage=false --verbose",
    "watch": "concurrently -k -p \"[{name}]\" -n \"TypeScript,Node\" -c \"cyan.bold,green.bold\" \"npm run watch-ts\"",
    "build-ts": "rimraf ./dist && tsc",
    "watch-ts": "tsc -w"
  },
  "author": "",
  "license": "ISC",
  "dependencies": {
    "tronweb": "^5.3.0"
  },
  "devDependencies": {
    "@daochild/tronweb-typescript": "1.1.1",
    "@types/node": "^14.18.59",
    "rimraf": "^5.0.1",
    "ts-node": "^10.9.1",
    "typescript": "5.2.2"
  }
}
```

```json
{
    "compilerOptions": {
        "experimentalDecorators": true,
        "emitDecoratorMetadata": true,
        "module": "commonjs",
        "esModuleInterop": true,
        "target": "es5",
        "noImplicitAny": true,
        "allowJs": true,
        "skipLibCheck": true,
        "sourceMap": true,
        "outDir": "dist",
        "declaration": true,
        "baseUrl": ".",
        "types":  ["node"],
        "lib": [ "esnext", "dom", "es6", "es5", "es2020", "es2022"],
    },
    "exclude": [
        "dist",
        "node_modules"
    ]
}
```


```typescript
// Code language: TypeScript

///<reference path="node_modules/@daochild/tronweb-typescript/dist/index.d.ts"/>
import TronWeb from 'tronweb'

const tronweb: TronWeb = new TronWeb({
    fullHost: 'https://api.trongrid.io',
})

console.log(tronweb)
```

**Comment by vekseel** [comment]
> try add type directly like in example `///<reference path="node_modules/@daochild/tronweb-typescript/dist/index.d.ts"/>`
> 
> Files in test project
> 
> ```json
> {
>   "name": "test-npm",
>   "version": "1.0.0",
>   "description": "",
>   "main": "index.js",
>   "scripts": {
>     "build": "npm run build-ts",
>     "test": "jest --coverage=false --verbose",
>     "watch": "concurrently -k -p \"[{name}]\" -n \"TypeScript,Node\" -c \"cyan.bold,green.bold\" \"npm run watch-ts\"",
>     "build-ts": "rimraf ./dist && tsc",
>     "watch-ts": "tsc -w"
>   },
>   "author": "",
>   "license": "ISC",
>   "dependencies": {
>     "tronweb": "^5.3.0"
>   },
>   "devDependencies": {
>     "@daochild/tronweb-typescript": "1.1.1",
>     "@types/node": "^14.18.59",
>     "rimraf": "^5.0.1",
>     "ts-node": "^10.9.1",
>     "typescript": "5.2.2"
>   }
> }
> ```
> 
> ```json
> {
>     "compilerOptions": {
>         "experimentalDecorators": true,
>         "emitDecoratorMetadata": true,
>         "module": "commonjs",
>         "esModuleInterop": true,
>         "target": "es5",
>         "noImplicitAny": true,
>         "allowJs": true,
>         "skipLibCheck": true,
>         "sourceMap": true,
>         "outDir": "dist",
>         "declaration": true,
>         "baseUrl": ".",
>         "types":  ["node"],
>         "lib": [ "esnext", "dom", "es6", "es5", "es2020", "es2022"],
>     },
>     "exclude": [
>         "dist",
>         "node_modules"
>     ]
> }
> ```
> 
> ```ts
> // Code language: TypeScript
> 
> ///<reference path="node_modules/@daochild/tronweb-typescript/dist/index.d.ts"/>
> import TronWeb from 'tronweb'
> 
> const tronweb: TronWeb = new TronWeb({
>     fullHost: 'https://api.trongrid.io',
> })
> 
> console.log(tronweb)
> ```

Unfortunately the same result
![image](https://github.com/daochild/tronweb-typescript/assets/48432436/442e5d6a-c3a3-48e1-b290-02c7cae6f536)
![image](https://github.com/daochild/tronweb-typescript/assets/48432436/44952648-1cec-4543-853b-98c4b8397070)

**Comment by daochild** [comment]
What tronweb version and typescript?

Updated: Node version? See in documentation.

**Comment by daochild** [comment]
Update to v1.2.2
